param (
    [Parameter(Mandatory=$true)][string]$directory,
    [Parameter(Mandatory=$true)][string]$oldKeyword,
    [Parameter(Mandatory=$true)][string]$newKeyword
)


#generated by chatgpt 3.5 
#prompt :write me a powershell script that renames every file name that ends 
#   with a specific suffix (not an extention) to end with a different suffix
#link: https://chatgpt.com/share/09df7f40-3e63-4def-aefd-fab54db17b41

# Prompt the user for the directory, old keyword, and new keyword

# Get all files in the specified directory
$files = Get-ChildItem -Path $directory -Recurse

foreach ($file in $files) {
    # Check if the file name contains the old keyword
    echo "checking" $file
    if ($file.Name -like "*$oldKeyword*") {
        # Replace the old keyword with the new keyword in the file name
        $newFileName = $file.Name -replace $oldKeyword, $newKeyword
        
        # Construct the full path for the new file name
        $newFilePath = Join-Path -Path $directory -ChildPath $newFileName
        echo $file.FullName "->" $newFilePath
        # Rename the file
        mv $file.FullName $newFilePath
        Write-Host "Renamed '$($file.Name)' to '$newFileName'"
    }
}
